### PR TITLE
Add examples/wlr-example.ini.example

### PR DESCRIPTION
**Pull request by versusvoid**
with option descriptions for examples

### CODE REVIEW

**Comment by SirCmpwn** [comment]
Can you move this to rootston/rootston.ini.example?

**Comment by versusvoid** [comment]
And change referenced file name at https://github.com/SirCmpwn/wlroots/blob/master/examples/config.c#L22 ?

**Comment by SirCmpwn** [comment]
Hmm. Yes, I think so.

At some point we'll want to make the examples actually use rootston/config.c to get their work done.

**Comment by SirCmpwn** [comment]
Thanks!

**Pull request merged**
