### PR TITLE
wl_shell fixes

### PR DESCRIPTION
**Pull request by emersion**
See @acrisci's comments in https://github.com/SirCmpwn/wlroots/pull/162

### CODE REVIEW

**Comment by acrisci** [comment]
qt does indeed use wl_shell. Test with a qt application by following [these instructions](https://wiki.qt.io/Basic_Qt_Programming_Tutorial).

My qt application does not get mouse events.

**Comment by emersion** [comment]
All comments should have been addressed now. Will test the QT app.

**Comment by SirCmpwn** [comment]
LGTM, let me know the QT results.

**Comment by emersion** [comment]
qt5-wayland seems to be using xdg shell: `Using the 'xdg-shell-v6' shell integration`

Though, as you said, my QT app doesn't get mouse events with xdg shell ( `[rootston/xdg_shell_v6.c:72] new xdg surface: title=MainWindow, app_id=qt-demo`).

**Comment by acrisci** [comment]
Mine is using wl_shell.

Get qt-creator and start a new project from the "QT Quick Controls 2 Application" from the template. Compile it (qmake && make) and then run with `./app -platform wayland`.

**Comment by emersion** [comment]
Changed the client code to print inputs: https://gist.github.com/emersion/7e453eb466beb3c2958c042ccf239ba7

I'm still not getting mouse events (works with gnome-shell). Will try QT Quick Controls 2.

**Comment by emersion** [comment]
With _QT Quick Controls 2 Application_, I'm still getting `Using the 'xdg-shell-v6' shell integration` (and no mouse events).

**Comment by SirCmpwn** [comment]
Let's spin out a ticket for xdg shell issues. I can't reproduce.

**Pull request merged**
